class SelectCarLocators:
    car_make_dd = "vehicleBrand"
    model_car_dd = "vehicleId"
    dealer_discount_cb = "optOut"
    conn_type_rb = "variant-universal"
    conn_type_label = "//label[@for='variant-universal']"
    power_rating_kw7 = "model-S7"
    power_rating_kw7_label = "//LABEL[@for='model-S7']"
    kw7_full_price = "(//span[@class='h3'])[2]"
    kw7_olev_price = "(//span[@class='h3 colour-primary'])[2]"
    comp_extra_list = "//div[@class='grid__col grid__col-md-4 grid__col-lg-4']"
    comp_price_list = "//p[@class='h4']"
    final_price = "//h3[@class='p-b-none']"
    next_btn = "next-button"
    close_pop_header = "//button[@class='alert__close pos-abs pin-top-right']"
    cookie_btn_class = "cookie__btn"
    next_loading_btn = "//button[@class='btn is-disabled']"
